/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_misfit_ble_util_CRCCalculator */

#ifndef _Included_com_misfit_ble_util_CRCCalculator
#define _Included_com_misfit_ble_util_CRCCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_misfit_ble_util_CRCCalculator
 * Method:    crc
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_misfit_ble_util_CRCCalculator_crc
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
