/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.misfit.ble.algorithm.swimlap;

public class lap_stats_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected lap_stats_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(lap_stats_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwimLapPostProcessorJNI.delete_lap_stats_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNStrokes(long value) {
    SwimLapPostProcessorJNI.lap_stats_t_nStrokes_set(swigCPtr, this, value);
  }

  public long getNStrokes() {
    return SwimLapPostProcessorJNI.lap_stats_t_nStrokes_get(swigCPtr, this);
  }

  public void setDuration_in_10th_seconds(long value) {
    SwimLapPostProcessorJNI.lap_stats_t_duration_in_10th_seconds_set(swigCPtr, this, value);
  }

  public long getDuration_in_10th_seconds() {
    return SwimLapPostProcessorJNI.lap_stats_t_duration_in_10th_seconds_get(swigCPtr, this);
  }

  public void setLap_end_in_10th_seconds(long value) {
    SwimLapPostProcessorJNI.lap_stats_t_lap_end_in_10th_seconds_set(swigCPtr, this, value);
  }

  public long getLap_end_in_10th_seconds() {
    return SwimLapPostProcessorJNI.lap_stats_t_lap_end_in_10th_seconds_get(swigCPtr, this);
  }

  public void setSvm(long value) {
    SwimLapPostProcessorJNI.lap_stats_t_svm_set(swigCPtr, this, value);
  }

  public long getSvm() {
    return SwimLapPostProcessorJNI.lap_stats_t_svm_get(swigCPtr, this);
  }

  public lap_stats_t() {
    this(SwimLapPostProcessorJNI.new_lap_stats_t(), true);
  }

}
