/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.misfit.ble.algorithm.swimlap;

public class LapStatVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected LapStatVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LapStatVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwimLapPostProcessorJNI.delete_LapStatVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LapStatVector() {
    this(SwimLapPostProcessorJNI.new_LapStatVector__SWIG_0(), true);
  }

  public LapStatVector(long n) {
    this(SwimLapPostProcessorJNI.new_LapStatVector__SWIG_1(n), true);
  }

  public long size() {
    return SwimLapPostProcessorJNI.LapStatVector_size(swigCPtr, this);
  }

  public long capacity() {
    return SwimLapPostProcessorJNI.LapStatVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SwimLapPostProcessorJNI.LapStatVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SwimLapPostProcessorJNI.LapStatVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SwimLapPostProcessorJNI.LapStatVector_clear(swigCPtr, this);
  }

  public void add(lap_stats_t x) {
    SwimLapPostProcessorJNI.LapStatVector_add(swigCPtr, this, lap_stats_t.getCPtr(x), x);
  }

  public lap_stats_t get(int i) {
    return new lap_stats_t(SwimLapPostProcessorJNI.LapStatVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, lap_stats_t val) {
    SwimLapPostProcessorJNI.LapStatVector_set(swigCPtr, this, i, lap_stats_t.getCPtr(val), val);
  }

}
