/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.misfit.ble.algorithm.swimlap;

public class SwimLapPostProcessor {
  public static long refine_lap_count(LapStatVector lapStats) {
    return SwimLapPostProcessorJNI.refine_lap_count(LapStatVector.getCPtr(lapStats), lapStats);
  }

}
