/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.misfit.ble.algorithm.swimlap;

public class SwimLapPostProcessorJNI {
  public final static native long new_LapStatVector__SWIG_0();
  public final static native long new_LapStatVector__SWIG_1(long jarg1);
  public final static native long LapStatVector_size(long jarg1, LapStatVector jarg1_);
  public final static native long LapStatVector_capacity(long jarg1, LapStatVector jarg1_);
  public final static native void LapStatVector_reserve(long jarg1, LapStatVector jarg1_, long jarg2);
  public final static native boolean LapStatVector_isEmpty(long jarg1, LapStatVector jarg1_);
  public final static native void LapStatVector_clear(long jarg1, LapStatVector jarg1_);
  public final static native void LapStatVector_add(long jarg1, LapStatVector jarg1_, long jarg2, lap_stats_t jarg2_);
  public final static native long LapStatVector_get(long jarg1, LapStatVector jarg1_, int jarg2);
  public final static native void LapStatVector_set(long jarg1, LapStatVector jarg1_, int jarg2, long jarg3, lap_stats_t jarg3_);
  public final static native void delete_LapStatVector(long jarg1);
  public final static native void lap_stats_t_nStrokes_set(long jarg1, lap_stats_t jarg1_, long jarg2);
  public final static native long lap_stats_t_nStrokes_get(long jarg1, lap_stats_t jarg1_);
  public final static native void lap_stats_t_duration_in_10th_seconds_set(long jarg1, lap_stats_t jarg1_, long jarg2);
  public final static native long lap_stats_t_duration_in_10th_seconds_get(long jarg1, lap_stats_t jarg1_);
  public final static native void lap_stats_t_lap_end_in_10th_seconds_set(long jarg1, lap_stats_t jarg1_, long jarg2);
  public final static native long lap_stats_t_lap_end_in_10th_seconds_get(long jarg1, lap_stats_t jarg1_);
  public final static native void lap_stats_t_svm_set(long jarg1, lap_stats_t jarg1_, long jarg2);
  public final static native long lap_stats_t_svm_get(long jarg1, lap_stats_t jarg1_);
  public final static native long new_lap_stats_t();
  public final static native void delete_lap_stats_t(long jarg1);
  public final static native long refine_lap_count(long jarg1, LapStatVector jarg1_);
}
